version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --save --legacy-peer-deps
      - npm install -g @angular/cli
      - npm install --save bootstrap --legacy-peer-deps
      - npm install bootstrap-icons --save
      - npm i crypto-js

  build:
    commands:
      - ng build --configuration production
  post_build:
    commands:
      - echo "updating files in the S3 bucket..."
      - aws s3 sync dist/password/ s3://password-manager-angular-project --delete